version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - nextjs_network
    restart: unless-stopped

networks:
  nextjs_network:
    driver: bridge
